# Generated by Django 4.2.30 on 2026-05-08 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('email_cliente', models.EmailField(max_length=254)),
                ('telefono_cliente', models.CharField(max_length=20)),
                ('descripcion_parcela', models.TextField(help_text='Dirección o indicaciones para llegar a la parcela')),
                ('kilos_estimados', models.PositiveIntegerField(help_text='Estimación de kilos a trabajar')),
                ('fecha_deseada', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de confirmación'), ('confirmada', 'Confirmada'), ('en_curso', 'En curso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True, help_text='Observaciones adicionales')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['fecha_deseada'],
            },
        ),
        migrations.CreateModel(
            name='ItemCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cesta.cita')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Ítem de cita',
                'verbose_name_plural': 'Ítems de cita',
                'unique_together': {('cita', 'servicio')},
            },
        ),
    ]
